baseurl = "http://marksou.github.io/"
languageCode = "en-us"
title = "Mike Atherton - Life Coach"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Mike Atherton"
	description = "Life Coach"


	# Navigation
	[params.navigation]
		brand = "Mike Atherton - Life Coach"

		[params.navigation.links]
			about     = "About"
			blog	  = "Blog"
			contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Your awesome slogan"
		subtitle   = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
		buttonText = "Find out more"

	# About section
	[params.about]
		headline    = "What I can do for you!"
		description = "In essence it’s about you and your life and making the best of you and your life.  Life coaching is about helping people achieve their visions and reaching their true potential. My personal style of life coaching is holistic and takes into account every aspect of your life situation.  Work/life balance, health and well being, nutrition, exercise, relationships, positivity, dealing with negativity and living in the moment, being present or what is commonly called mindfulness; and so have developed a system called “Life’s A Piece Of Cake”, that as you perceive it identifies both the positive and the negative in your life and then using visual techniques identifies the areas of your life that can be improved and adjusted.  This is done with real time specific activities and goals set up over a period of time to suit you. I personally believe in one-to-one coaching, and what I call “Personal, positive development partnerships”. It’s important to realise that the work to be done to make your world better, more rewarding, is directed by me, but is actually achieved by you.  You will work as hard as I do to achieve real outcomes and see real positive change."
		
	# Blog Section
	[params.blog]
		headline = "Blog"
		description = "Read my blog"
		buttonText = "Blog"


	# Contact section
	[params.contact]
		headline = "Get In Touch!"
		description = "Phone or Email me"
		phone = "0780 676070"
		email = "mike@golifeandsoul.com"
		facebook = "mark.southee"
		twitter = "marksou"
